### PR TITLE
adapt swift 3 APIs

### PR DESCRIPTION
**Pull request by 5d**

### CODE REVIEW

**Comment by wokalski** [comment]
@5d What is the preferred policy for swift versioning?

**Comment by 5d** [comment]
@wokalski Sorry, I don't quite understand your question, 
this pull request just changed some syntaxes and adapt code to the swift 3.0 SDK APIs.

**Comment by bobergj** [comment]
There's the:

```
#if swift(>=3.0)
// this compiles on Swift 3.0
#else
// this compiles on Swift 2.2 or 2.3
#endif
```

But essentially you would have to wrap the whole implementation in that, and the external API of the two versions would be different (due to naming conventions etc).
I would instead just migrate to swift 3 in master, and create a tag (or branch) for the swift 2.3 version, if someone needs that.

**Comment by wokalski** [comment]
Hm... I see. I'd like it to be compatible with 2.3 but maybe we'll do it in the future.

**Comment by wokalski** [comment]
@bobergj can you confirm it works properly?

**Comment by wokalski** [comment]
@bobergj @5d 

I got around updating this today. I am preparing an update with support for moves, proper patch implementation and more. When I'm done I will rebase it against this branch. Thanks for the contribution.

**Pull request merged**
