### PR TITLE
Xcode 9.0 suggested changes

### PR DESCRIPTION
**Pull request by tonyarnold**
This PR contains a final move to Swift 4.0, and replaces some deprecated API use in the test target.

### CODE REVIEW

**Comment by wokalski** [comment]
argh, there's some warning 😫

**Comment by tonyarnold** [comment]
Sorry about that - I forgot to specify the Swift version for Travis. It should be OK now.

**Comment by tonyarnold** [comment]
> there's some warning

Oh, are you talking about the deprecation notices in the tests?

**Comment by wokalski** [comment]
Thank you @tonyarnold. Wonderful job.

**Comment by tonyarnold** [comment]
Not a problem! Do you have a timeline for moving across to this branch on `master` and making a podspec update, etc?

**Comment by wokalski** [comment]
I would've done it already but I'm not using this project anymore so I have little motivation to do that ☹️

**Comment by tonyarnold** [comment]
Ah, that's a shame - sorry to hear that! I'll draw up a PR for it then. Do you think you'll use the project again in the future?

**Comment by wokalski** [comment]
I don't think so to be honest. I'm using OCaml for everything and am very happy with it 💃🏼💃🏼💃🏼.

**Comment by tonyarnold** [comment]
Good to hear OCaml makes you happy 😀

Well, in that case I might fork your repo and keep things moving on my own fork if that's OK with you? Happy to keep merging my changes upstream, but it sounds like you might prefer not to have to maintain this anymore?

I've integrated it into ReactiveKit's Bond library, and a few projects of my own, so I need to keep the code current.

**Comment by wokalski** [comment]
That is totally ok with me 👍. I will put a note with a link to your fork in the readme. Happy to hear that it's working for you.

**Pull request merged**
