### PR TITLE
Reformat source code, and update test target

### PR DESCRIPTION
**Pull request by tonyarnold**
This PR achieves the following outcomes:

- Makes the DiffTest target part of each framework scheme so that tests can be run against each scheme within Xcode (2c6468a384e6785f0aea2e9d8739e417d8e43461)
- Formats all source to be consistent using @nicklockwood's [SwiftFormat tool](https://github.com/nicklockwood/SwiftFormat) (c0506cbcda082c93f5e6f7da6b8b79e34d26420f)

The tool was executed with no options (which means it should infer format from the existing structure of the file), from the root of the project using the following command: 

```sh
find . -name "*.swift" -type f -exec swiftformat {} \;
```

Addresses #11.

### CODE REVIEW

**Comment by nicklockwood** [comment]
@tonyarnold I may have misinterpreted your comment, but the default behaviour of SwiftFormat with no options is *not* to infer the format from the project. To do that, you need to first run it with the `--inferoptions` flag, and then explicitly add the outputted arguments to the command.

**Comment by tonyarnold** [comment]
Ohhhhh, no, you read my comment right. OK, I didn't read that correctly. 

In either case, the goal here was consistency so perhaps inferring format is _not_ what's needed here.

**Comment by nicklockwood** [comment]
@tonyarnold FWIW, looking at the formatting changes applied, I'd guess the only things that running `--inferoptions` would have done differently are:

* Disabled adding of spaces around range operators (`..<`, `...`).
* Disabled adding trailing commas to array literals
* Not adding blank lines between functions, or removing them at the end of class bodies

**Comment by nicklockwood** [comment]
@tonyarnold I should also point out that both formatting and `--inferoptions` accept an entire project folder as input, and will ignore non-swift files, so there is no need for the `find . -name "*.swift" -type f -exec`

**Comment by wokalski** [comment]
@tonyarnold thanks a lot! 

So apart from the failing test, there're inconsistencies or rather styling preferences I'd like to address. It's not an issue with the PR, it's more of asking for an opinion.

1. What's your preferred way of formatting function calls?

In this project I add a newline after the opening parenthesis, arguments on separate lines, and the closing one after the last argument. I don't like the inconsistency though that the first parenthesis precedes the argument yet the last ones are on the same line. I'm overthinking it now but I'm curious what's your preference.

2. Function declarations

White space is inconsistent. I am not sure how to split arguments, return type and the `where` clause. Especially the where clause is a bit annoying for me because for some reason I feel like indenting it. However it looks like by default it should be in the same column.

cc @nicklockwood

**Comment by wokalski** [comment]
Actually I noticed the same problem with `ifs`.

**Comment by nicklockwood** [comment]
> I don't like the inconsistency though that the first parenthesis precedes the argument yet the last ones are on the same line.

SwiftFormat 19 will correct that automatically :-)

**Comment by wokalski** [comment]
@nicklockwood so do you prefer the closing parenthesis on the next line?

**Comment by nicklockwood** [comment]
@wokalski yes.

**Comment by wokalski** [comment]
@tonyarnold are you sure that a travis' job fails if tests don't pass? This is the reason for `set -o pipefail` at the beginning. They didn't fail for me without it. (Took it from [here](https://github.com/realm/SwiftLint/commit/b04ca1144e1143b8369e3ef66d082f8acf593cae) 😅)

**Comment by tonyarnold** [comment]
I think the CI configuration is OK now, it's just the DiffTest target that needs to be made multi-target. Sorry man, you're probably getting spammed by emails right now. I'll squash these commits once I have it working.

**Comment by wokalski** [comment]
Could you put a `XCTFail` somewhere to verify if travis' job fails when a test fails?

**Comment by tonyarnold** [comment]
OK, finally. Sorry about that, this started out as a PR to address formatting concerns and now… well, we're over here.

Three things addressed now:

1. Project structure: I've made the project contain a single target, which is capable of building all of the supported platforms. This is a big change, so be sure you want this before merging - I've found it reduces the overheads of maintaining all those platform-specific targets. 
2. Travis CI now builds a matrix of all the supported platforms, as well as linting the podspec, building the example project and testing the `swift build` does the right thing.
3. The source code is reformatted. I know you have some concerns here, and I'm happy to address those if it's possible to do so, but the focus should be on consistency.

I'm not going to be upset at all if you want to reject this PR, or some/all of the changes therein. It's your baby, @wokalski - thanks for the project!

**Comment by wokalski** [comment]
No! I don't want to reject any of them. It's an awesome improvement. Let's do things incrementally. I was just expressing some concerns I have but let's leave them for a separate issue.

Awesome job. I'll merge it when Travis is done. Thanks for the contribution! Very appreciated.

**Comment by wokalski** [comment]
Thanks, @tonyarnold

**Pull request merged**
