### PR TITLE
[WIP] Swift 4.0

### PR DESCRIPTION
**Pull request by tonyarnold**
🚨 **Please don't merge this PR** 🚨 

This PR compiles and passes all tests under Swift 4.0.

### CODE REVIEW

**Review by wokalski — APPROVED** [review]
👏

that tuple syntax tho. It's going to be reverted, isn't it? (sorry, I haven't followed/used Swift recently)

**Comment by wokalski** [comment]
If it's complete, lmk and I'll merge it into `swift-4.0` branch in this repo in case somebody uses it with the beta.

**Comment by tonyarnold** [comment]
> that tuple syntax tho. It's going to be reverted, isn't it?

Yeah, they stated last week or the week prior it's going back to Swift 3 syntax for tuples.

> If it's complete, lmk and I'll merge it into swift-4.0 branch

Go for it. It's working for me, and the CI tests are running & passing again. 👍

**Comment by wokalski** [comment]
Thank you!

**Comment by tonyarnold** [comment]
I wonder if we need to be testing all of the iOS variants I’ve included in the CI list? It’s taking forever to pass, and I’m not sure if that’s offset by the benefit that level of testing provides.

**Comment by wokalski** [comment]
Honestly, I don't think there's any advantage. I'd leave just one test run per OS.

**Pull request merged**
