### PR TITLE
Add Transform to IndexPath's when working with UI

### PR DESCRIPTION
**Pull request by farzadshbfn**
Most of the time due to UI design and ..., developers have extra cells in some sections hence Model is not exactly mapped to the UI presented. This way developers can use these methods if they have extra cells inside the Table/Collection views too.

### CODE REVIEW

**Comment by farzadshbfn** [comment]
There's just something that i'm worried about, How will it impact the performance with default implementation

**Comment by wokalski** [comment]
Thanks. It's certainly a nice addition.

**Comment by wokalski** [comment]
@farzadshbfn why will it impact perf?

**Comment by farzadshbfn** [comment]
@wokalski because all IndexPaths and IndexSets are generated through a Closure (by default returns the generated one by Diff methods) I thought it might multiply runtime of methods by a small coefficient but I don't think it would be "that" much to be noticed.

**Comment by wokalski** [comment]
I believe it will be optimized. I'm going to look at it today and merge

**Review by wokalski — CHANGES_REQUESTED** [review]
Thanks. It's awesome 💝 . Could you just add little tests for BatchUpdate? Afterwards we're good to go!

**Comment by farzadshbfn** [comment]
I'm on it 😉

**Comment by farzadshbfn** [comment]
I Accidentally added baseline for `measureBlock`s, tried to stop it from auto-push but it was too late 😕 

p.s: will add NestedBatchUpdates too if I can

**Comment by wokalski** [comment]
@farzadshbfn if you contribute next time, feel free to create a branch in this repo. I'll be able to take over the PR with those little changes then so that I don't bother you :).

**Comment by farzadshbfn** [comment]
I'm about to add tests for `NestedBatchUpdate`, but there are some test-cases that made me confused. for example:
    1. `[[1, 2], [3, 4]] -> [[1, 2, 3, 4]]`: `NestedBatchUpdate`'s answer is to remove two sections and insert a new section. I was expecting to see `IndexPath` moves and one section deletion.
    2. `[[1, 2], [3, 4]] -> [[3, 4], [1, 2]]`: `NestedBatchUpdate`'s answer is to remove two elements from first section and also two elements from second section and insert two elements into first section and two elements into second section. I was expecting to see Section move.

**Comment by farzadshbfn** [comment]
I think it's better to remove support of `NestedBatchUpdate` and let developers handle it with `BatchUpdate` and `IndexPathTransform`s alone. what do you think? because data changes in sections won't happen that much, there are most likely to happen by user interactions and are usually one cell or couple of cells and developer is able to understand from which sections they are.

**Comment by wokalski** [comment]
Hmm, I believe the correct answer would be fixing those bugs. I added an issue (#47) because I believe it can be fixed at the library level. Let's skip tests for this part for now.

**Comment by wokalski** [comment]
@farzadshbfn it's good to merge, right?

**Comment by farzadshbfn** [comment]
Except the `NestedBatchUpdate` part, every thing was good. I also used in in one of my projects(with and without Transforms), and it's working perfectly 👌🏼.

**Review by wokalski — APPROVED** [review]

**Pull request merged**
